name: hexchat
version: "2.14.2"
summary: HexChat IRC Client
description: >
  HexChat is an easy to use yet extensible IRC Client. It allows you to securely join multiple networks and talk to users privately or in channels using a customizable interface. You can even transfer files.
confinement: strict
grade: stable
base: core18
plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk2-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes

environment:
  GTK_PATH: $SNAP/lib/gtk-2.0
  GTK_DATA_PREFIX: $SNAP
  XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

slots:
  hexchat:
    interface: dbus
    bus: session
    name: org.hexchat.service
apps:
  hexchat:
    command: desktop-launch hexchat
    desktop: share/applications/io.github.Hexchat.desktop
    plugs:
      - desktop
      - desktop-legacy
#      - pulseaudio
      - network
      - network-bind
      - x11
parts:
  desktop-gtk2:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - locales-all
      - xdg-user-dirs
        
  hexchat:
# FIXME: Spell check needs dictionaries
# FIXME: Notifications can't see the desktop file or icon
# FIXME: Platform see above:
    after: [desktop-gtk2 ]
    source: https://dl.hexchat.net/hexchat/hexchat-2.14.2.tar.xz
    plugin: meson
    # The exported desktop file is renamed and requires absolute path to icon
    override-build: |
      # Fix desktop file reference (Doesn't work in Unity?)
      sed -i 's|io.github.Hexchat|hexchat_hexchat|g' src/fe-gtk/notifications/notification-libnotify.c
      # Absolute path to icon required...
      sed -i 's|Icon=hexchat|Icon=/share/icons/hicolor/scalable/apps/hexchat.svg|' data/misc/io.github.Hexchat.desktop.in.in
      snapcraftctl build
    meson-parameters:
      - --prefix=/
      - --buildtype=release
# FIXME: Compiles build path into project...
      - -Dwith-isocodes=false
# FIXME: Audio notifications don't work
      - -Dwith-libcanberra=false
    build-packages:
      - gettext
      - libssl-dev
      - libdbus-glib-1-dev
      - libglib2.0-dev
      - libgtk2.0-dev
      - libnotify-dev
      - libproxy-dev
      - python3-dev
      - libperl-dev
      - libluajit-5.1-dev
    stage-packages:
      - libnotify4
      - libproxy1v5
      - libdbus-glib-1-2
    prime:
      - -include
      - -lib/*linux*/pkgconfig
      - -share/metainfo
      - -share/man
# FIXME: snapcraft pulls in tons of unnecessary garbage, keep removing more
  lua-lgi:
    plugin: nil
    stage-packages:
      - lua-lgi
      - gir1.2-freedesktop
      - gir1.2-glib-2.0
      - gir1.2-soup-2.4
      - gir1.2-gtk-2.0
    prime:
      - usr/share/lua/5.1
      - usr/lib/*linux*/lua/5.1
      - usr/lib/*linux*/girepository-1.0
      - usr/lib/*linux*/libffi.so*
      - usr/lib/*linux*/libgirepository-1.0.so*
      - usr/lib/*linux*/liblua5.1*.so*
      - usr/lib/girepository-1.0
