name: hexchat
version: "2.14.0"
summary: HexChat IRC Client
description: >
  HexChat is a graphical IRC client with a GTK+ GUI. Features include Python
  and Perl scripting support, a plugin API, multiple server/channel windows,
  spell checking, multiple authentication methods including SASL, and
  customizable notifications. For more information on IRC, see
  http://irchelp.org/.
confinement: strict
grade: stable
plugs:
  gnome-3-24-platform:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-24:gnome-3-24-platform
slots:
  hexchat:
    interface: dbus
    bus: session
    name: org.hexchat.service
apps:
  hexchat:
    command: desktop-launch hexchat-wrapper
    desktop: share/applications/io.github.Hexchat.desktop
    plugs:
      - unity7
      - desktop-legacy
      - x11
#      - pulseaudio
      - network
      - network-bind
      - gnome-3-24-platform
parts:
  desktop-gnome-platform:
    stage:
      # We override this in hexchat-copy with gtk2 version
      - -flavor-select
  hexchat:
# FIXME: Spell check needs dictionaries
# FIXME: Notifications can't see the desktop file or icon
    build-attributes: [no-system-libraries]
    after: [desktop-gnome-platform]
    source: https://dl.hexchat.net/hexchat/hexchat-2.14.0.tar.xz
    plugin: meson
    # The exported desktop file is renamed and requires absolute path to icon
    prepare: |
      sed -i 's|io.github.Hexchat|hexchat:hexchat|g' src/fe-gtk/notifications/notification-libnotify.c
      sed -i 's|Icon=hexchat|Icon=/share/icons/hicolor/scalable/apps/hexchat.svg|' data/misc/io.github.Hexchat.desktop.in.in
      sed -i 's|Exec=hexchat|Exec=hexchat-wrapper|' data/misc/io.github.Hexchat.desktop.in.in
    meson-parameters:
      - --prefix=/
      - --buildtype=release
# FIXME: Compiles build path into project...
      - -Dwith-isocodes=false
# FIXME: Audio notifications don't work
      - -Dwith-libcanberra=false
    build-packages:
      - libssl-dev
      - libdbus-glib-1-dev
      - libglib2.0-dev
      - libgtk2.0-dev
      - libnotify-dev
      - libproxy-dev
      - python3-dev
      - libperl-dev
      - libluajit-5.1-dev
    prime:
      - -include
      - -lib/*linux*/pkgconfig
      - -share/metainfo
      - -share/man
  scripting-langs:
    plugin: nil
    stage-packages:
      - libpython3.5
      - libluajit-5.1-2
      - libperl5.22
    prime:
      - -usr/bin
      - -usr/sbin
      - -usr/lib/mime
      - -usr/lib/gcc
      - -usr/lib/*linux*/libsqlite3.so*
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/bug
      - -usr/share/lintian
  lua-lgi:
    plugin: nil
    stage-packages:
      - lua-lgi
    prime:
      - usr/share/lua/5.1
      - usr/lib/*linux*/lua/5.1
      - usr/lib/*linux*/girepository-1.0
      - usr/lib/*linux*/libffi.so*
      - usr/lib/*linux*/libgirepository-1.0.so*
      - usr/lib/*linux*/liblua5.1*.so*
  gi-bindings:
    plugin: nil
    stage-packages:
      - gir1.2-freedesktop
      - gir1.2-glib-2.0
      - gir1.2-soup-2.4
      - gir1.2-gtk-2.0
    prime:
      - usr/lib/*linux*/girepository-1.0
      - usr/lib/girepository-1.0
  wrappers:
    source: data
    plugin: dump
    organize:
# FIXME: Can't use $SNAP_LAUNCHER_ARCH_TRIPLET in environment overrides so need wrapper
      wrapper: bin/hexchat-wrapper
