name: hexchat
version: "2.12.4"
summary: HexChat IRC Client
description: >
  HexChat is a graphical IRC client with a GTK+ GUI. Features include Python
  and Perl scripting support, a plugin API, multiple server/channel windows,
  spell checking, multiple authentication methods including SASL, and
  customizable notifications. For more information on IRC, see
  http://irchelp.org/.
confinement: strict
grade: stable
plugs:
  gnome-3-24-platform:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-24:gnome-3-24-platform
slots:
  hexchat:
    interface: dbus
    bus: session
    name: org.hexchat.service
apps:
  hexchat:
    command: desktop-launch $SNAP/bin/hexchat-wrapper
    desktop: share/applications/hexchat.desktop
    plugs:
      - unity7
      - desktop-legacy
      - x11
#      - pulseaudio
      - network
      - network-bind
parts:
  desktop-gnome-platform:
    stage:
      # We override this in hexchat-copy with gtk2 version
      - -flavor-select
  hexchat:
# FIXME: Spell check needs dictionaries
# FIXME: Notifications can't see the desktop file or icon
    after: [desktop-gnome-platform]
    source: https://dl.hexchat.net/hexchat/hexchat-2.12.4-repack.tar.xz
    plugin: autotools
    # The exported desktop file is renamed and requires absolute path to icon
    prepare: |
      sed -i 's|("hexchat")|("hexchat:hexchat")|' src/fe-gtk/notifications/notification-libnotify.c
      sed -i 's|Icon=hexchat|Icon=/share/icons/hicolor/scalable/apps/hexchat.svg|' data/misc/hexchat.desktop.in.in
    configflags:
      - --enable-gtkfe
      - --enable-python=python3
      - --disable-debug
      - --disable-glibtest
# FIXME: Compiles build path into project...
      - --disable-isocodes
# FIXME: Audio notifications don't work
      - --disable-libcanberra
    build-packages:
      - patch
      - intltool
      - libtool
      - libssl-dev
      - python3-dev
      - libperl-dev
      - libluajit-5.1-dev
    prime:
      - -include
      - -lib/pkgconfig
      - -share/appdata
      - -share/man
# Incorrectly pulled in libs that are in gnome-platform
      - -usr/lib/*linux*/libnotify.so*
      - -usr/lib/*linux*/libdbus-glib-1.so*
      - -usr/lib/*linux*/libtdb.so*
      - -usr/lib/*linux*/libltdl.so*
  lua-lgi:
    plugin: nil
    stage-packages:
      - lua-lgi
    prime:
      - usr/share/lua/5.1
      - usr/lib/*linux*/lua/5.1
      - usr/lib/*linux*/girepository-1.0
      - usr/lib/*linux*/libffi.so*
      - usr/lib/*linux*/libgirepository-1.0.so*
      - usr/lib/*linux*/liblua5.1*.so*
  gi-bindings:
    plugin: nil
    stage-packages:
      - gir1.2-freedesktop
      - gir1.2-glib-2.0
      - gir1.2-soup-2.4
      - gir1.2-gtk-2.0
    prime:
      - usr/lib/*linux*/girepository-1.0
      - usr/lib/girepository-1.0
  wrappers:
    source: data
    plugin: dump
    organize:
      wrapper: bin/hexchat-wrapper
