name: hexchat
version: "2.12.4"
summary: HexChat IRC Client
description: |
  HexChat is a graphical IRC client with a GTK+ GUI. Features include Python
  and Perl scripting support, a plugin API, multiple server/channel windows,
  spell checking, multiple authentication methods including SASL, and
  customizable notifications. For more information on IRC, see
  http://irchelp.org/.
confinement: strict
grade: stable
apps:
  hexchat:
    command: desktop-launch $SNAP/bin/hexchat-wrapper
    plugs: [unity7, gsettings, pulseaudio, network, network-bind, home]
parts:
  hexchat:
    source: https://dl.hexchat.net/hexchat/hexchat-2.12.4.tar.xz
    plugin: autotools
    configflags: [--enable-python=python3, --disable-dbus, --disable-debug]
    snap:
      - -lib/pkgconfig
      - -include
    build-packages:
      - intltool
      - libtool
# FIXME: We would have to install every spell check language
#      - iso-codes
      - libssl-dev
# FIXME: We can't own session bus name
#      - libdbus-glib-1-dev
      - libproxy-dev
# FIXME: Notifications can't see the desktop file or icon
      - libnotify-dev
# FIXME: Audio notifications don't work
#      - libcanberra-dev
      - python3-dev
      - libperl-dev
      - libluajit-5.1-dev
    stage-packages:
#      - sound-theme-freedesktop
#      - iso-codes
#      - libenchant1c2a
      - lua-lgi
      - gir1.2-glib-2.0
      - gir1.2-soup-2.4
      - gir1.2-gtk-2.0
    after:
      - desktop-gtk2
  hexchat-copy:
    source: .
    plugin: dump
    organize:
      wrapper: bin/hexchat-wrapper
