name: hexchat
version: "2.14.0"
summary: HexChat IRC Client
description: >
  HexChat is an easy to use yet extensible IRC Client. It allows you to securely join multiple networks and talk to users privately or in channels using a customizable interface. You can even transfer files.
confinement: strict
grade: stable
# FIXME: Platforms are not auto-downloaded
#plugs:
#  gnome-3-26-1604:
#    interface: content
#    content: gnome-3-26-1604
#    target: gnome-platform
#    default-provider: gnome-3-26-1604
slots:
  hexchat:
    interface: dbus
    bus: session
    name: org.hexchat.service
apps:
  hexchat:
    command: desktop-launch hexchat-wrapper
    desktop: share/applications/io.github.Hexchat.desktop
    plugs:
      - unity7
      - desktop-legacy
      - x11
      - pulseaudio
      - network
      - network-bind
#      - gnome-3-26-1604
parts:
#  desktop-gnome-platform:
#    stage:
#      # We override this in hexchat-copy with gtk2 version
#      - -flavor-select
  meson:
    source: https://github.com/mesonbuild/meson/releases/download/0.45.0/meson-0.45.0.tar.gz
    plugin: python
    stage: [-]
  hexchat:
# FIXME: Spell check needs dictionaries
# FIXME: Notifications can't see the desktop file or icon
# FIXME: Platform see above:
#    after: [desktop-gnome-platform]
#    build-attributes: [no-system-libraries]
    after: [desktop-gtk2, meson]
    source: https://dl.hexchat.net/hexchat/hexchat-2.14.0.tar.xz
    plugin: meson
    # The exported desktop file is renamed and requires absolute path to icon
    prepare: |
      # Fix desktop file reference (Doesn't work in Unity?)
      sed -i 's|io.github.Hexchat|hexchat_hexchat|g' src/fe-gtk/notifications/notification-libnotify.c
      # Absolute path to icon required...
      sed -i 's|Icon=hexchat|Icon=/share/icons/hicolor/scalable/apps/hexchat.svg|' data/misc/io.github.Hexchat.desktop.in.in
    meson-parameters:
      - --prefix=/
      - --buildtype=release
# FIXME: Compiles build path into project...
      - -Dwith-isocodes=false
    build-packages:
      - gettext
      - libssl-dev
      - libdbus-glib-1-dev
      - libglib2.0-dev
      - libgtk2.0-dev
      - libnotify-dev
      - libproxy-dev
      - libcanberra-dev
      - python3-dev
      - libperl-dev
      - libluajit-5.1-dev
    stage-packages:
      - sound-theme-freedesktop
      - libcanberra-pulse
    prime:
      - -include
      - -lib/*linux*/pkgconfig
      - -share/metainfo
      - -share/man
  lua-lgi:
    plugin: nil
    stage-packages:
      - lua-lgi
      - gir1.2-freedesktop
      - gir1.2-glib-2.0
      - gir1.2-soup-2.4
      - gir1.2-gtk-2.0
    prime:
      - usr/share/lua/5.1
      - usr/lib/*linux*/lua/5.1
      - usr/lib/*linux*/girepository-1.0
      - usr/lib/*linux*/libffi.so*
      - usr/lib/*linux*/libgirepository-1.0.so*
      - usr/lib/*linux*/liblua5.1*.so*
      - usr/lib/girepository-1.0
  wrappers:
    source: data
    plugin: dump
    organize:
# FIXME: Can't use $SNAP_LAUNCHER_ARCH_TRIPLET in environment overrides so need wrapper
      wrapper: bin/hexchat-wrapper
